version: '3.3'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile-laravel
    container_name: laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    depends_on:
      - laravel
    networks:
      - laravel_network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    container_name: fastapi
    restart: unless-stopped
    volumes:
      - ./fastapi:/app
      - ./tmp:/tmp
    networks:
      - fastapi_network

  nginx-fastapi:
    image: nginx:latest
    container_name: nginx-fastapi
    restart: unless-stopped
    ports:
      - "7001:7000"
    volumes:
      - ./nginx/fastapi.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - fastapi_network

networks:
  laravel_network:
  fastapi_network:

volumes:
  mysql_data:
