FROM php:8.1-fpm

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libzip-dev \
    libjpeg-dev \
    libxpm-dev \
    libwebp-dev \
    libonig-dev \
    libicu-dev \  
    python3 \  
    python3-pip \  
    python3-venv  

# Crear y activar un entorno virtual
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Instalar youtube-dl en el entorno virtual
RUN /opt/venv/bin/pip install youtube-dl

# Instalar extensiones de PHP
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip intl

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Crear directorio de trabajo
WORKDIR /var/www

# Copiar y configurar scripts de inicio
COPY laravel/docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Variables de entorno para producción
ENV APP_ENV=production
ENV APP_DEBUG=false

ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["php-fpm"]
